// store/initialState.ts
import { ImageState } from "@/types/image.types";

export const initialState: ImageState = {
  images: [],
  paginatedFiles: [],
  selectedFile: null,
  selectedImage: null,
  isUploading: false,
  uploadProgress: 0,
  error: null,
  uploadComplete: false,
  newImageAdded: false,
  isDragging: false,
  isEditMode: false,
  isBlurring: false,
  isPainting: false,
  isCropping: false,
  brushColor: "#ff0000",
  brushSize: 10,
  isEraser: false,
  blurAmount: 5,
  blurRadius: 10,
  zoom: 1,
  previewUrl: "",
  width: 0,
  height: 0,
  imageRef: null,
  canvasRef: null,
  completedCrop: null,
  originalStats: null,
  newStats: null,
  dataSavings: 0,
  hasEdited: false,
  format: "jpeg",
  currentPage: 1,
};
